# Generated by Django 4.1 on 2022-08-04 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=1000, verbose_name='Search for book by title, author, or both.')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
