# Generated by Django 4.1 on 2022-08-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookquery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookquery',
            name='search_type',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-fiction', 'Non-fiction')], default='Fiction', max_length=500),
        ),
    ]
