# Generated by Django 4.1 on 2023-07-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookquery", "0005_bookquery_delete_bookquerynonfiction"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_downloads", models.IntegerField(default=346)),
            ],
        ),
    ]
