# Generated by Django 4.1 on 2023-07-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookquery", "0006_downloadcount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadcount",
            name="num_downloads",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
